---
# tasks file for bvansomeren.acme

- name: ensure acme.sh pkg is installed
  package:
    name: acme.sh
    state: present

- name: get home folder
  getent:
    database: passwd
    key: "acme"
    split: ":"

- set_fact:
    acme_home: "{{ getent_passwd['acme'][4] }}"

- name: ensure account.conf is configured
  template:
    src: account.conf
    dest: "{{ acme_home }}/.acme.sh/account.conf"
    owner: acme
    group: acme

- name: ensure logfile exists
  copy:
    force: False
    dest: /var/log/acme.sh.log
    content: ""
    owner: acme
    group: acme
    mode: 0640

- name: ensure newsyslog.conf.d is present in /usr/local/etc
  file:
    path: /usr/local/etc/newsyslog.conf.d/
    state: directory

- name: ensure syslogging is setup
  template:
    src: acme.sh.conf
    dest: /usr/local/etc/newsyslog.conf.d/acme.sh.conf
