---
# tasks file for bvansomeren.acme

- name: ensure acme.sh and rsync pkgs are installed
  package:
    name: acme.sh rsync
    state: present

- name: get home folder
  getent:
    database: passwd
    key: "acme"
    split: ":"

- set_fact:
    acme_home: "{{ getent_passwd['acme'][4] }}"

- name: ensure acme ssh key is setup for pushing
  shell: ssh-keygen -b 2048 -t rsa -f {{ acme_home }}/.ssh/id_rsa -q -N ""
  args:
    creates: "{{ acme_home }}/.ssh/id_rsa"
  become: True
  become_user: acme

- name: ensure copy of ssh-pubkey exists on controller
  fetch: 
    dest: "{{ playbook_dir }}/files/"
    src: "{{ acme_home }}/.ssh/id_rsa.pub"

- name: keyscan and register the loadbalancers
  command: "ssh-keyscan {{ item }}"
  changed_when: False
  with_items: "{{ loadbalancers }}"
  register: keyscan

- debug:
    msg: "line: {{  item }}"
    verbosity: 2
  with_items: "{{ keyscan.results | map(attribute='stdout_lines')|list }}" 

- name: ensure loadbalancers are added to the known_hosts for acme
  lineinfile:
    dest: "{{ acme_home }}/.ssh/known_hosts"
    create: yes
    owner: acme
    group: acme
    mode: 0644
    state: present
    line: "{{ item }}"
  with_items: "{{ keyscan.results | map(attribute='stdout_lines')|list }}"

- name: ensure account.conf is configured
  template:
    src: account.conf
    dest: "{{ acme_home }}/.acme.sh/account.conf"
    owner: acme
    group: acme

- name: ensure haproxy_export_folder
  file:
    path: "{{ haproxy_export_folder }}"
    owner: acme
    group: acme
    state: directory

- name: ensure logfile exists
  copy:
    force: False
    dest: /var/log/acme.sh.log
    content: ""
    owner: acme
    group: acme
    mode: 0640

- name: ensure newsyslog.conf.d is present in /usr/local/etc
  file:
    path: /usr/local/etc/newsyslog.conf.d/
    state: directory

- name: ensure syslogging is setup
  template:
    src: acme.sh.conf
    dest: /usr/local/etc/newsyslog.conf.d/acme.sh.conf
